CREATE TABLE tenants (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE CHECK (length(btrim(name)) BETWEEN 1 AND 120),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE users (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id      BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  email          TEXT NOT NULL UNIQUE
                 CHECK (email = lower(email) AND position('@' IN email) > 1 AND length(email) <= 254),
  password_hash  TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX users_tenant_id_idx ON users (tenant_id);

CREATE TABLE holdings (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id     BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  as_of_date    DATE NOT NULL,
  ticker        TEXT NOT NULL CHECK (ticker = upper(ticker) AND length(ticker) BETWEEN 1 AND 16),
  asset_class   TEXT NOT NULL CHECK (length(btrim(asset_class)) BETWEEN 1 AND 32),
  quantity      NUMERIC(24, 8) NOT NULL CHECK (quantity >= 0),
  price         NUMERIC(24, 8) NOT NULL CHECK (price >= 0),
  market_value  NUMERIC GENERATED ALWAYS AS (quantity * price) STORED,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT holdings_tenant_date_ticker_key UNIQUE (tenant_id, as_of_date, ticker)
);